name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          BASE_URL: tms-stat-viewer-example
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm install && npm run build
          BUILD_DIR: dist/