name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    environment:
      BASE_URL: tms-stat-viewer-example
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'tvip'
          reponame: 'tms-stat-viewer-example'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged